name: AI PR Assistant (Gemini)

on:
  pull_request:
    types: [opened, synchronize, reopened] # Triggers when a PR is opened, new commits are pushed, or PR is reopened

permissions:
  contents: read
  pull-requests: write # This permission is crucial for updating the PR description or adding comments

jobs:
  generate_pr_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate diff generation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Ensure you use a compatible Python version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub google-generativeai

      - name: Get Pull Request Diff
        id: get_diff
        run: |
          # Fetch the diff for the current PR
          # The GITHUB_TOKEN has permissions to do this
          DIFF_URL="${{ github.event.pull_request.diff_url }}"
          PR_DIFF=$(curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$DIFF_URL")
          # Escape special characters for multi-line output in GitHub Actions
          # The 'sed' command handles escaping newline and quote characters for JSON output
          ESCAPED_DIFF="${PR_DIFF//'%'/'%25'}"
          ESCAPED_DIFF="${ESCAPED_DIFF//$'\n'/'%0A'}"
          ESCAPED_DIFF="${ESCAPED_DIFF//$'\r'/'%0D'}"
          echo "pr_diff=$ESCAPED_DIFF" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Run Gemini PR Summary Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
          PR_DIFF: ${{ steps.get_diff.outputs.pr_diff }} # Pass the fetched diff as an environment variable
        run: python .github/scripts/generate_gemini_pr_summary.py